mainapp/helpers.py
mainapp/tests.py
mainapp/urls.py
mainapp/views_ajax.py

- Added AJAX Tests
- Helper Functions for Invalid Inputs
- Normal URL Fix
Fixes #4

Add AJAX Tests

---

static/mainapp/css/explore.css
templates/mainapp/explore.html
templates/mainapp/genre.html
templates/mainapp/index.html
templates/mainapp/layout.html

- Add Rating Feedback after a book is rated
- Fix Alignment issue in Explore Page
Fixes #6 
**Demo**:

Add Rating Feedback

---

README.md
mainapp/helpers.py
mainapp/views.py
templates/mainapp/index.html

Fixes #8 
- Changed Top Books among users to Popular Books among users
- Changed and Improved `top_books `function.

Added Popular Books among users

---

mainapp/views_ajax.py

Book Summary Fix

---

static/mainapp/css/genre.css

Will fix 3rd sub issue of #19 
If the author's name exceeds three-line "..." will be added at the end of the line 3rd.
Earlier:
Now:

Author names overlap fix

---

static/mainapp/css/explore.css
templates/mainapp/explore.html

Will Fix 1st sub-issue of issue #19 
Explore page in large screen will show books in the grid while for the small screen it will be in the carousel.

explore page layout changed

---

templates/mainapp/index.html

Fixes #22 
- Set Book Char limit to 60 and author limit to 20

Char Limit Fix

---

README.md

- List out your changes
- Link the Issue which this resolves
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA

[Test to Merge] Merge test

---

BookRecSystem/settings.py

- Fixes #78 
- Heroku env var fix
NA
Ran unit tests

Key-error fix

---

CONTRIBUTING.md

Added necessary command for environment setup in windows OS.
- Fixes #73

Update docs with OS specific env commands

---

CONTRIBUTING.md

- Fixed the order of commands in CONTRIBUTING.md
- Fixes #91

Fix order in setting up commands

---

static/mainapp/css/layout.css
templates/mainapp/layout.html

- Added top button to all the pages by just changing layout.html and layout.css. This button will take you to the top of the page. And the scrolling is smooth.
- #63 
NA
Ran it in my localhost
When on the top of the page the button is not displayed.
On hover

Added Top button

---

templates/mainapp/layout.html

- List out your changes
Added home button in the navbar.
- Link the Issue which this resolves
#80

Added home button in the nav bar

---

static/mainapp/css/signup.css
templates/account/login.html
templates/account/signup.html

- Changed the Sign up with Google button to Sign in with google on the login page.
-  In sign-up page added this as Sign up with Google
- Fixes Issue [#60](https://github.com/Praful932/Kitabe/issues/60)
NA
Tested locally

Google Authentication

---

BookRecSystem/settings.py

- Set DEBUG variable in settings.py to False in Production
- #89 
N/A
- Works when ran locally
- Ran tests using ```python manage.py test``` 
NA
NA

DEBUG variable in Production

---

static/mainapp/css/login.css
static/mainapp/css/signup.css
templates/account/login.html
templates/account/signup.html

- styling of signup and login page updated
- #50 
NA
I have tested it in my local  system .
https://user-images.githubusercontent.com/67833077/111673259-ccc9e500-8840-11eb-81ef-6745e821293e.mp4
https://user-images.githubusercontent.com/67833077/112419823-17bc8e80-8d52-11eb-907e-e5e7676c53b7.mp4
https://user-images.githubusercontent.com/67833077/112419681-d330f300-8d51-11eb-8616-6c05dc55905e.mp4
- [ x] I have followed the [Contribution Guidelines](https://github.com/Praful932/Kitabe/blob/master/CONTRIBUTING.md).
- [ x] My changes do not edit/add any unrequired files.
- [x ] My changes are covered by tests.

Better UI for Signup and Login page

---

templates/mainapp/layout.html

- Search Icon added 
- Fixed #111
N/A
`python manage.py runserver`
`360*640` Resolution
@maneprajakta I have added the search icon, removed the unnecessary changes and created a new PR to resolve conflict. Please review it.

Added search icon

---

static/mainapp/css/index.css
static/mainapp/png/book.svg
templates/mainapp/index.html

- Added the Preloader
- Fixes #43 
NA
Ran it on local server

Added Preloader

---

static/mainapp/css/index.css

- Initially, there was a bug in  "Read Genre Wise"  which made complete div transform. Now I had changed that and had made a hover effect that will affect only the genre card. And I had considered all the widths and made the hover effects accordingly.
- Fixes #157 
NA
This has been tested by seeing the output in the browser.
Hope everything is clear.
Thanks.

Adding Hover effect on Genre Cards

---

static/mainapp/css/layout.css

- As the title of this PR suggests, I added a custom scrollbar which matches the background and theme of the project.
- Fixes #169 
- Layout.css
- I've tested this using `flake8`, `python manage.py test` and it shows 0 errors.
https://imgur.com/KSjyANv
https://imgur.com/a/CsS938y
https://user-images.githubusercontent.com/61618767/113402816-504c1000-93c3-11eb-9aa1-20383fdfd52f.mp4
Should I add a Hover Effect (shown in above video) over the scrollbar as well?

Added Customized Scrollbar

---

BookRecSystem/settings.py
static/mainapp/css/layout.css

- List out your changes : 
There are overall two UI changes I have made for the search box, they are as follows :
1.  Increasing the **border-radius** of the search box, which in result will look more minimal and goes well with the theme.
2. Secondly, making the search box move towards the right side of the top bar, close to the other tab section.
- Link the Issue which this resolves: #168 
No dependencies were affected during my code changes.
This has been tested by using **flake8-django**. This is a plugin used to detect bad practices on Django projects. And also we  have used a file for checking the test cases (**manage.py test**) and successfully it has passed all the mentioned test cases.

Enhance search box

---

static/mainapp/css/index.css
static/mainapp/css/recommendation.css
templates/mainapp/recommendation.html

- Changed the size and alignment of rating buttons on Homepage
- Changed the size and alignment of rating and "more details" buttons on Your read section
- Fixes #30 
NA
Tested using flake8, python manage.py test

Frontend Bug Fixes

---

static/mainapp/css/layout.css
templates/mainapp/layout.html

- Fixed drop down for library 
- No
- Locally

 ⚒️[Fix]: Drop down for library improvised

---

mainapp/views.py
static/mainapp/css/login.css
static/mainapp/css/signup.css
templates/account/signup.html

UI of form updated.
None
locally

⚒️[Fix]: fixed form UI

---

static/mainapp/css/layout.css

- Added a scrollbar that nearly matches that of chrome
- Fixes #237
NA
In firefox

Added custom scrollbar for firefox

---

static/mainapp/css/explore.css
static/mainapp/css/genre.css
static/mainapp/css/index.css
static/mainapp/css/read.css

- Add Hover
- Fixes #249 
NA
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA

Added Hovering to more details button

---

static/mainapp/css/explore.css
static/mainapp/css/genre.css
static/mainapp/css/index.css
static/mainapp/css/layout.css
static/mainapp/css/login.css
static/mainapp/css/read.css
static/mainapp/css/recommendation.css
static/mainapp/css/signup.css
templates/mainapp/layout.html
templates/mainapp/read.html

Changed button CSS also formatted the CSS code.
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA

Button css

---

static/mainapp/css/explore.css
static/mainapp/css/genre.css
static/mainapp/css/index.css
static/mainapp/css/layout.css
static/mainapp/css/login.css
static/mainapp/css/read.css
static/mainapp/css/recommendation.css
static/mainapp/css/saved_book.css
static/mainapp/css/signup.css
templates/mainapp/layout.html
templates/mainapp/read.html
templates/mainapp/saved_book.html

Improved CSS for saved books page.
- If any UI Changes, Use [this](https://www.screentogif.com/) to record or else specify NA

⚒️[Fix]: css for saved books
